language: go
sudo: false
notifications:
  email: false
addons:
  code_climate:
    repo_token: 74d6c110184c7bcd503dbca04e46bcd84e2d1d55bf813f6e78a693765d0e956d
go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
env:
  - GO15VENDOREXPERIMENT=1
script: go test -v --race -coverprofile=gimple.coverprofile
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < gimple.coverprofile
